### ISSUE TITLE
Add UbikLoadPack

### ISSUE THREAD

**Issue by ubikloadpack** [QAInsights/Performance-Testing-Tools#3]
Hello,
Thanks for your nice list.
Would you be ok to add UbikLoadPack ? 
https://ubikloadpack.com/

It's commercial, has a free trial plan limited to 3 Virtual Users.
We are also strong contributors to Apache JMeter.

Thanks
Regards

**Comment by QAInsights** [comment]
@ubikloadpack Thanks for the request. It has been added. 👍
